### ISSUE TITLE
Make imports for Duck more efficient

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/ngrx-ducks#2]
Creating a Duck needs `effect`, `@Action`, `@Ducksify` & `bindSelectorGroup` to be imported.

```ts
import {
  Action,
  Ducksify
  effect,
  bindSelectorGroup
} from '@co-it/ngrx-ducks';
```

An easy way simplifying it is to group some features like `effect`, `Action`, `bindSelectorGroup`.

```ts
import { bind, Ducksify } from '@co-it/ngrx-ducks';

// ...

@Ducksify({})
export class Duck {
  select = bind.selectorGroup(selectors);

  load = bind.effect<number>('Load something');

  @bind.Action('Mutate something')
  save(state: State, payload: SomePayload) {
    return {
      ...state, ...payload
    }
  }
} 

```

**Comment by GregOnNet** [comment]
@skydever Your feedback on this idea is highly appreciated. 🙂

**Comment by skydever** [comment]
Hi @GregOnNet !

I always hope that my ide is doing the job for me (sadly I have some issues currently - for the sake of it, maybe you have an idea - posted it [here](https://github.com/nrwl/nx/issues/83#issuecomment-491737318)), but having the option to have less imports sounds reasonable to me, something like `cy` from cypress, `Ducks` containing everything possible ...

**Comment by GregOnNet** [comment]
#6 already reduces the amount of imports.
An alias would not be needed anymore.
