### ISSUE TITLE
Get rid of state type

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#27]
[Implement State Mutations](https://co-it.gitbook.io/ngrx-ducks/ngrx-ducks-core/guides/quick-start#implement-state-mutations) provides the following example:
```
loadCount = createDuck('[Counter] Set initial value',
  (state: CounterState, payload: number) => {
    return { ...state, count: payload };
});
```
I think providing the type of the state in each `createDuck` functoin is kinda boilerplating. It would be great if we could get rid of it:
```
loadCount = createDuck('[Counter] Set initial value',
  (state, payload: number) => {
    return { ...state, count: payload };
});
```
Unfortunately, now it has `any` type. Is it possible to inherit the type similar to NgRx vanilla reducers somehow?

**Comment by GregOnNet** [comment]
Hi,

currently, I do not know how the state-type could be inferred automatically.
I already checked if the constraint could be passed by making the class generic. But this does not work.

If someone can help here it would be great.

**Comment by GregOnNet** [comment]
Closing this issue for now, because we did not find a solution, yet.
