### ISSUE TITLE
Allow to move reducer export to the facade

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#28]
According to [Create Reducer automatically](https://co-it.gitbook.io/ngrx-ducks/ngrx-ducks-core/guides/quick-start#create-reducer-automatically):
```
...
@StoreFacade()
export class CounterFacade {
  ...
}
...
export const counterReducer = getReducer(initialState, CounterFacade);
```
Is it possible to make changes so that I can do the following:
```
@StoreFacade()
export class CounterFacade {

  static reducer = getReducer(initialState, CounterFacade);

}
``` 
Now I'm getting the error:
```
TS1238: Unable to resolve signature of class declaration when called as an expression.
Property 'reducer' is missing in type 'AnnotationTarget' but required in type 'typeof CounterFacade'.
```

**Comment by GregOnNet** [comment]
Hi, 

thanks for reporting this issue.
I think this should be doable.

Maybe some fiddling with the type definitions.

**Comment by GregOnNet** [comment]
Hi @BorisZubchenko,

you can now add statics to @StoreFacade annotated classes.
Please find the demo here: https://stackblitz.com/edit/ngrx-ducks-12?embed=1&file=src/app/counter/store/counter/counter.facade.ts
