### ISSUE TITLE
Use props-like dispatch function

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#29]
For now, the dispatch function gives as a payload field, but it would be great if we could get named field(s), like from the vanilla NgRx props function. For example, I've got these actions:
```
// Handled by the effects
export const load = createAction('[User] Load User');
export const loadSuccess = createAction('[User] Load Success', props<{ user: User }>());
// Handled by the reducer
export const upsert = createAction('[User] Upsert', props<{ user: User }>());
```
And the following effects:
```
...
load$ = // Sending a request

loadSuccess$ = createEffect(() => this.actions$.pipe(
  ofType(loadSuccess),
  map(action => upsert({ user: action.user }))
));
...
```
Take a look at the map function above. I like the idea I can shorten it to the following:
```
map(({ user }) => upsert({ user }))

->

map(action => upsert(action))

->

map(upsert)
```
It seems more readable for me. Now I'm trying to include your library in my project. The only way out for me is to rename my reducer's parameter name to payload since the dispatch function gives me only this field. It becomes more counterintuitive than before.

How about making the dispatch function looks like the NgRx props one or to get rid of the dispatch function and make the library work with the vanilla props (their APIs look the same but I'm sure there are pitfalls)?

**EDIT:**
I misunderstood the way params are passing to the action:
```
// My expectations
map(({ payload }) => userActions.upsert({ user: payload }))

// How it actually works
map(({ payload }) => userActions.upsert(payload))
```
I'm sorry for hurry.

However, my thoughts apply to this case too :)
If it would work as I expected, we can still do the following:
```
map(userActions.upsert)
```
So the second idea is to make Ducks actions accept the payload in the way NgRx actions do.

**Comment by GregOnNet** [comment]
Hi,

using `payload` here is the intended API.
I found it useful to rely on the simple contract that an action has a type and an optional payload.

However, reduxjs.org and ngrx.io now prefer the API you are suggesting.

I really like the handling how it currently is, since no one needs to think about the inner structure of the action. It is just `type` and `payload`.

It could be evaluated if the NgRx Ducks API could be opened for the `props`-way.
But, it should not become a breaking change.

**Comment by BorisZubchenko** [comment]
Honestly, I'd investigate why do NgRx (and even Redux) team prefer this API, because there was payload-way before v8. No doubt there are some reasons why they did this since they could remain payload as is:
```
props<number>();
```
Actually, I even remembered the reason of this API but have forgotten it (should have recorded it immediately :)). I'll do some kind of research and comment if I find any information about it.

**Comment by GregOnNet** [comment]
Closing this issue for now, because we did not find a solution, yet.
