### ISSUE TITLE
Consider combining getActions/getReducer functions

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#31]
Please, take a look at the following example from the NgRx Entity Docs:
```
// get the selectors
const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
} = adapter.getSelectors();
```
Similar can be done with the getActions and getReducer functions. By doing this, we can get rid of duplicating the facade type. I'd also swap parameters so the initial state goes after the actions). My proposal (could not come up with the function name):
```
// This implementation does not provide any types to the result.
export const getActionsAndReducer = <S, T extends Constructable = any>(token: T, initialState: S) => ({
  actions: getActions(token),
  reducer: getReducer(initialState, token)
});

export const {
  actions: userActions,
  reducer: userReducer
} = getActionsAndReducer<UserState>(UserFacade, {
  a: null,
  b: 0,
  c: {}
});
```

**Comment by GregOnNet** [comment]
Hi,

thanks for reaching out.
Combining both functions also leads into performance improvements.

@BorisZubchenko Would you mind creating a PR for this? I can also do the implementation. However, I am a bit busy the next few weeks.

**Comment by BorisZubchenko** [comment]
@GregOnNet I was trying to implement this function (you can find it in the example above), but it does not provide any typings. I'm not so strong in the TypeScript Generics yet.

**Comment by GregOnNet** [comment]
Alright, missed that point.
I will have a look at it.

Thanks for your report.

**Comment by GregOnNet** [comment]
Closing this issue since the most recent update to StoreFacade-decorator automatically registers Tue reducer in the Store.
