### ISSUE TITLE
Provide createMutableDuck

### ISSUE THREAD

**Issue by BorisZubchenko** [co-IT/ngrx-ducks#32]
[ngrx-etc](https://github.com/timdeschryver/ngrx-etc) provides [mutableOn](https://github.com/timdeschryver/ngrx-etc#mutableon) function to reduce boilerplate when implementing reducer pure function. Since it's impossible to use the function with this library, it would be great to implement the `createMutableDuck`:
```
// Before
increment = createDuck(
  '[Counter] Increment',
  (state: CounterState) => ({
    ...state,
    score: state.score + 1
  })
);

// After
increment = createMutableDuck(
  '[Counter] Increment',
  (state: CounterState) => {
    state.score++;
  }
);
```
A function without braces can also be implemented (not sure if it's possible but have some ideas):
```
increment = createMutableDuck(
  '[Counter] Increment',
  (state: CounterState) => state.score++;
);
```

**Comment by GregOnNet** [comment]
Definitely a good catch.
You can already combine `immer` (used by ngrx-etc) with NgRx Ducks.
But you would still need to return the state object.

**Comment by BorisZubchenko** [comment]
> But you would still need to return the state object.

I could be wrong, but I think the state itself can be used as a second argument of an immer function. The idea is that we pass not the value of the state but the reference. This means we can use this reference instead of the reducer result. I looked at mutableOn sources and found the following line:
```
const producedState = produce(state, (draft: Draft<S>): Draft<S> => reducer(draft, action))
```
I think it can be refactored to this:
```
const producedState = produce(state, (draft: Draft<S>): Draft<S> => {
  reducer(draft, action);
  // The draft value has changed inside the reducer function
  return draft;
})
```
But I worry about 2 things:
1. I'm not sure if this works :)
2. Perhaps ngrx-etc's creator tried to implement this but had no success (see 1). @timdeschryver, could you please take a look at the implementation above?

**Comment by GregOnNet** [comment]
Sorry I was just loud thinking.
The type-definition of `createDuck` requires to return a state-object that is correctly typed.

That's why we need `createMutableDuck` to leverage the whole benefit of `immer`.
I believe this need to live in its own library because I do not want to have `@ngrx-ducks/core` to depend on immer.
So I will introduce `@ngrx-ducks/mutable` for that, I think.

**Comment by timdeschryver** [comment]
It can indeed be refactored to it, if you want the whole reducer to be mutable.
This is also implemented in `ngrx-etc`, as `mutableReducer` - https://github.com/timdeschryver/ngrx-etc/blob/master/src/mutable-reducer/index.ts#L18-L23

The difference is that `mutableOn` just wraps the one `on` function.

**Comment by GregOnNet** [comment]
Closing this issue due lack of time to implement it yet.

Help is very welcome.

**Comment by GregOnNet** [comment]
### API Draft

```ts
import { creteMutableDuck, getMutableReducer } from '@ngrx-ducks/core';

@StoreFacade()
export class CounterFacade {
  static reducer = getMutableReducer(Facade, initialState); // calls produce behind the scences...

  add = createMutableDuck('[Counter] Add', (state: CounterState, payload: number) => {
    state.count += payload;
  });
}
```

**Comment by GregOnNet** [comment]
@BorisZubchenko, @timdeschryver: It's done: https://stackblitz.com/edit/ngrx-ducks-12?file=src/app/counter/store/counter/counter-mutable.facade.ts
