### ISSUE TITLE
Support angular 10

### ISSUE THREAD

**Issue by ChristianKlima** [co-IT/ngrx-ducks#35]
We tried to update our solution to version 10 of angular and nrwl packages. Will there be a new version of ngrx-ducks that supports version 10? Thank you in advance

**Comment by GregOnNet** [comment]
Hi Christian,

thanks for messaging me.
The update is coming #36.

So far, I only needed to update the dependencies and experienced no breaking changes caused by external libraries.

Cheers
Gregor

**Comment by sebakiller2018** [comment]
Thanks Gregor!

**Comment by GregOnNet** [comment]
NgRx Ducks 10 has been released.
You can find a working example here: https://stackblitz.com/edit/ngrx-ducks-10?file=src/app/counter/counter.component.ts
