### ISSUE TITLE
Payload with falsy values

### ISSUE THREAD

**Issue by skydever** [co-IT/ngrx-ducks#37]
Hi!

I just ran into a problem when the payload of an action is a falsy value (0, false ...). The reducer function of `createDuck` does not get the payload, it is always undefined.

I modified the stackblitz example to show what I mean [here](https://stackblitz.com/edit/ngrx-ducks-9-flttk8?file=src%2Fapp%2Fcounter%2Fcounter.component.ts). Just press the **Set 0** button, the counter value will be **undefined** afterwards.

[This](https://github.com/co-IT/ngrx-ducks/blob/28d12df88ed87c7760a7163699ca29b1aaea4975/packages/core/src/create-duck/create-duck.ts#L92) line seem suspicious, and also [this](https://github.com/co-IT/ngrx-ducks/blob/ca07e91594c901b54789aec7f815f4b4c8e0a594/packages/core/src/store-facade/connect/connect-dispatchers.ts#L14) one. I hope this would help. I am not sure if there are more places to check? Else I could make a PR ...

Best wishes and thank you for your work!

//cc @GregOnNet Long time no see, hope you are doing fine!! We finally started to use the new API 🎉 👍

**Comment by GregOnNet** [comment]
Hi @skydever,

thanks for the report.
I will provide a fix today.

Maybe those checks are not needed at all.
Maybe I should pass through what ever is coming, and if null or undefined is passed payload still has the correct value at all.

**Comment by skydever** [comment]
awesome 👍 

yes, I also think that the check is not needed 🤔

**Comment by GregOnNet** [comment]
fixed in version 10.1.1 👍
