### ISSUE TITLE
Doesn

### ISSUE THREAD

**Issue by vladimirdrayling** [co-IT/ngrx-ducks#38]

**Comment by GregOnNet** [comment]
Hi @vladimirdrayling ,

I think something went wrong saving the issue.
<img width="832" alt="CleanShot 2020-08-27 at 16 48 05@2x" src="https://user-images.githubusercontent.com/444278/91457854-21961600-e885-11ea-99db-840f04a5da08.png">

Unfortunately, I cannot see a description.

**Comment by vladimirdrayling** [comment]
Oh! Didn't noticed it. Sorry for this mistake.

There is the correct one, created on the same time. Please have a look at #39.
