### ISSUE TITLE
@FlatDuck

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/ngrx-ducks#4]
> ⚠️ This proposal is in draft state.

### FlatDuck<T>

```ts
@FlatDuck<DuckState>({})
export MyFlatDuck {
  select = bind.selectorGroup(selectors);
  
  effects = bind.effects({
    loadAll: init('Load all')
    /* see https://github.com/co-IT/ngrx-ducks/issues/3 */
  });

  actions = bind.actions<DuckState>({
    loadSuccess,
    restoreSuccses: [loadSuccess, {
      type: 'Overwrite Action type of this.loadSuccess',
      scope: 'API' 
    }],
    indicateLoading
  }, prefix: '[MyFlatDuck]')

}

  @bind.Action('Loading successful')
  function loadSuccess(state: DuckState, payload: SomePayload) {}
```

### Usage 

```ts
export Component {
  constructor(@Inject(MyFlatDuck) private myDuck: FlatDuck<MyFlatDuck>){
    this.myDuck.loadAll.dispatch() // ... effects property of MyFlatDuck is gone
    this.myDuck.loadSuccess.dispatch(somePayload) // ... actions property of MyFlatDuck is gone
  }
}
```

TypeScript allows to extract type information of nested properties (see: https://stackoverflow.com/questions/51435783/pick-and-flatten-a-type-signature-in-typescript?answertab=active#tab-top).

**Comment by GregOnNet** [comment]
For now, I don't think that this will be implemented.
Configuring the Actions would become harder.

**Comment by GregOnNet** [comment]
// @skydever

**Comment by skydever** [comment]
Hi @GregOnNet !

I really like the drive the ducks got lately and I want to highlight the selector feature. This is an awesome addition and I am looking forward to take advantage of it 👍 The docs need a little update, maybe I can help there after my holidays, also updating the schematics would be great...

I like the idea of adding a prefix and a scope to be more consistent, this would definitely safe some keystrokes. Maybe at the `@Duck` level, setting all defaults optionally (prefix+scope), changeable at the `@Action` decorator (or adding a structure level to define the scope somehow, for a bunch of actions?) if required, or at the `bind.effects` call for effects... As you mentioned, it would become harder to configure actions if that has to be done via `bind.actions`, I really like the current action solution, it is easy to understand, I would not change that.

I like the idea of setting up the effects using a function, and I am wrapping my head around this, and I was thinking that it would be great to define such effects (no reducer) in one place only, the effects class. The duck gets the list of the effect class(es) via a function, and if you add such an effect in the effect class file the duck will know about it. Some idea I came up, was to extract the `@Effect()` properties of the class, extend `@Effect('Load')` to pass the action type or use the property name for the action type - this will add the `whereType` under the hood ... if that would be possible? 🤔

**Comment by skydever** [comment]
... just the `@Effect('My action type')` properties with a type set, the other effects won't be dispatched directly, have it's own `whereType` ...

**Comment by GregOnNet** [comment]
Hey, I do not get the idea `@Effect -> whereType under the hood`.
Can you provide a code sample?

I will check if the prefix can be set in `@Ducksify()`.

**Comment by skydever** [comment]
hey!

I was talking about something like this:

**Duck**
```typescript
// nothing else is required at the Duck to do: myDuck.sampleEffect.dispatch()
effects = bind.effects([MyDuckEffects, MyOtherDuckEffects]);
```

**Effect**
```typescript
@DuckEffectWithoutReducer('My effect/action type')
sampleEffect = this.actions$.pipe(
  // magical auto-inclusion of whereType()/ofType() catching 'My effect/action type'
  exhaustMap(...),
  tap(...)
)
```

... or just:
```typescript
@DuckEffectWithoutReducer('My effect/action type')
sampleEffect = pipe(
  exhaustMap(...),
  tap(...)
)
```
and the decorator wraps the code inside `this.actions$.pipe(of/whereType(...), <here>)` ... but how to handle the payload ... just a crazy idea maybe :thinking:

**Comment by GregOnNet** [comment]
I see thank you for the clarification.
For now, I do not want to go that way.

I want the library to integrate the best way possible with the existing API of NgRx.
Event the `whereType`-operator could be removed at some point in the future.
My intention is that a developer only need to learn as little as needed to use NgRx Ducks.

**Comment by skydever** [comment]
... apart from the idea of using the effect class to generate the methods, would be a circular dependency I guess, was just a *quick shot* ... the `effects = bind.effects(` syntax looks good and would totally *save some keystrokes* if you use the `scope` and `prefix` option, maybe the `scope` can be set once by grouping the object somehow?

```typescript
effects = bind.effects([{
    scope: 'API',
    loadAll: init('Load all'), 
    loadById: init<number>('Load by id')
  }, {
    scope: 'another scope',
    anotherEffect: init<number>('Something happended')
}], {
  prefix: 'MyDuck'
});
```

... beside that, what are other advantages you see by creating an object for it?

**Comment by GregOnNet** [comment]
Closing this in favor of #6
