### ISSUE TITLE
Support for Angular v12 / NGRX v12

### ISSUE THREAD

**Issue by markasalinas** [co-IT/ngrx-ducks#48]
Will NGRX Ducks be updated to support Angular v12  and NGRX v12?

**Comment by GregOnNet** [comment]
Hi, I am currently on it.
Unfortunately, the tests checking the types fail for some reason.

`ts-snippet` does not find any variables any more.
<img width="750" alt="CleanShot 2021-05-22 at 22 51 42@2x" src="https://user-images.githubusercontent.com/444278/119240518-49828380-bb50-11eb-828c-070d08f0828a.png">

**Comment by GregOnNet** [comment]
When I downgrade typescript from 4.2 to 3.9 `ts-snippet` starts working again but it throws other errors then...

**Comment by GregOnNet** [comment]
Hey @markasalinas: Here is @ngrx-ducks/core@11-alpha supporting Angular 12 and NgRx 12.
Please give it a try: https://stackblitz.com/edit/ngrx-ducks-11?file=src/app/app.component.ts

**Comment by GregOnNet** [comment]
Hi @markasalinas NgRx Ducks 12 has been published: https://stackblitz.com/edit/ngrx-ducks-12?file=src/app/counter/store/counter/counter.facade.ts

**Comment by markasalinas** [comment]
@GregOnNet thank you so much!
