### ISSUE TITLE
Allow configuring action type prefixes in Decorator

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/ngrx-ducks#58]
```ts
@StoreChunk({
  feature: 'book',
  featureAsPrefix: true, // prefixes each action with '[book] '
  ...
})
```

**Comment by redaxmedia** [comment]
It would be nice to be true by default...

**Comment by GregOnNet** [comment]
Hi,

thanks for your idea.


Cons
- this would be a breaking change
- this would be less explicit
- this would take control away from the developer



Henry Ruhs ***@***.***> schrieb am Fr., 24. Sept. 2021, 12:52:

**Comment by redaxmedia** [comment]
false in 12.x and true from 13 and higher?

we properly need a way to configure it inside feature.module and therefore only once per module?

**Comment by GregOnNet** [comment]
Available in Version 13: https://stackblitz.com/edit/ngrx-ducks-12-9ztnzp?file=src%2Fapp%2Fcounter%2Fstore%2Fcounter%2Fcounter.store.ts
