### ISSUE TITLE
Error: NOT SUPPORTED when trying to use @ngrx-ducks/schematics:facade

### ISSUE THREAD

**Issue by Markus-Ende** [co-IT/ngrx-ducks#67]
Hi @GregOnNet ,

I get an `Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID` when running `npx nx generate @ngrx-ducks/schematics:facade`.

One thing I found when skimming the sources were, that the peerDependencies in `libs/schematics/package.json` are outdated.

Tried to build the schematic from source to try a fix, but didn't get this to work. Maybe you can give me some hints on how to build the schematics project?

Regards
Markus

**Comment by Markus-Ende** [comment]
Latest version of @ngrx-ducks/schematics is 12.0.0, also when bundled with @ngrx-ducks/core

**Comment by GregOnNet** [comment]
Hi @Markus-Ende,

I was about to remove schematics from this project, since I have no time to  maintain the schematics.

The error looks like the schema has been changed in Schematics (id before, $id now).

**Comment by GregOnNet** [comment]
@skydever Do you have any information about recent changes in schematics API?

**Comment by Markus-Ende** [comment]
> I was about to remove schematics from this project, since I have no time to maintain the schematics.

ah ok, can relate..

It's not too hard to write a little schematic for one's specific use cases anyway, especially when inside an Nx repo.

**Comment by GregOnNet** [comment]
https://github.com/co-IT/ngrx-ducks/issues/72
