### ISSUE TITLE
Peer dependency to rxjs with fixed version

### ISSUE THREAD

**Issue by oemmes** [co-IT/ngrx-ducks#79]
In the published package.json there is a peer dependency to rxjs with a fixed version:

```
"rxjs": "7.5.5"
```
see https://unpkg.com/@ngrx-ducks/core@14.0.0/package.json

In the original package.json it is not included:
https://github.com/co-IT/ngrx-ducks/blob/main/libs/core/package.json

Can you check why that depdency is in there? Either it should be removed or at least not set to a fixed version.

@angular/core has this as peer dependency:
```
"rxjs": "^6.5.3 || ^7.4.0",
```

I assume that it's inserted by some tool of the build/deplyoment chain from the root package.json:
https://github.com/co-IT/ngrx-ducks/blob/main/package.json#L29

For version 13 it was rxjs 6.6.0:
https://github.com/co-IT/ngrx-ducks/blob/v13.1.3/package.json#L29
-> https://unpkg.com/@ngrx-ducks/core@13.1.3/package.json

Thanks for your work, I really like using ngrx-ducks for managing state and actions :-)

**Comment by GregOnNet** [comment]
Hey, Thanks for the hint. I will have a look at this.
Currently, I do not know where it is coming from.

Thanks for the kind words, too. 🙏

**Comment by GregOnNet** [comment]
Released with 14.0.1

I added the peer to rxjs: `>= 7.0.0`

The dependency was indeed automatically set by the bundler.

**Comment by GregOnNet** [comment]
Oh man, sorry for that.

I was preparing #85 as well and accidentally adopted the wrong version numbers.

Sorry.

**Comment by GregOnNet** [comment]
Released 14.0.2: https://www.npmjs.com/package/@ngrx-ducks/core

**Comment by oemmes** [comment]
Hi Gregor,

sorry to open up this issue again. But now the version constraint is `>^6.5.5 || ^7.4.0` which is not valid. The `>` needs to be removed...

**Comment by GregOnNet** [comment]
Hi, thanks so much.

I usually check the validity of the package.json with `npm --loglevel verbose install --dry-run` but it did not complain.

Fix is about to come

**Comment by GregOnNet** [comment]
@oemmes Thank you very much for your continuous feedback.
Currently, I need to a lot in parallel.

Sorry for the last instable releases

**Comment by GregOnNet** [comment]
Released **14.0.3:** https://www.npmjs.com/package/@ngrx-ducks/core
